### ISSUE TITLE
fix first question in the first page which is moved slightly right side.

### ISSUE THREAD

**Issue by rajibmitra** [rajibmitra/simple-survey#23]

**Comment by ooHAoo** [comment]
Is it okay for me to work on this?
I'm looking into it right now :)

**Comment by vinay72** [comment]
The questions are not visible in the `FirstPage,html` file.

**Comment by rajibmitra** [comment]
@ooHAoo  Sure go ahead ! 
@vinay72  did you rebase ?

**Comment by rajibmitra** [comment]
Well done @Terian93  , I have merged the PR , closing this issue.
