### ISSUE TITLE
Single quotation mark showing weirdly on first index page

### ISSUE THREAD

**Issue by ooHAoo** [rajibmitra/simple-survey#26]
I was just testing the page (using Firefox browser) and noticed that the "We're ...." is showing with some weird characters.

That's because it's using
We’re

Instead of

We're

As you can see from the screenshot.

![screen shot 2018-10-29 at 10 05 02 am](https://user-images.githubusercontent.com/26858034/47655263-052ed280-db63-11e8-89a8-b13abcc49e2e.png)

I didn't want to make the changes before asking just in case that character is used for some specific reasons. Let me know if I can go ahead and change it appropriately. Thanks!

**Comment by rajibmitra** [comment]
Awesome , I was about to put it in issues , thanks @ooHAoo , please go ahead.

**Comment by rajibmitra** [comment]
please close this issue @ooHAoo as I merged your pull request. 
Thanks .
