### ISSUE TITLE
thirdPage questions are not showing up. 

### ISSUE THREAD

**Issue by rajibmitra** [rajibmitra/simple-survey#29]
Need a fix. could be the css issue.

**Comment by ganes1410** [comment]
@rajibmitra  can i do this ??

**Comment by rajibmitra** [comment]
please @ganes1410  go ahead.

**Comment by BalesabuGodugu** [comment]
fix done and updated alignment too.

**Comment by stevopritchard** [comment]
Hi,

Still need any help with this?

**Comment by rajibmitra** [comment]
no @stevopritchard , I see there is a good fix from @BalesabuGodugu , Soon I am going to merge his PR , but I need a help on its enhancement, one a user clicks on **Submit** button , another page should show a new page that will mention , "You system has been improved" , Can anyone of you implement it ?

**Comment by rajibmitra** [comment]
created a new issue on the enhanced version of this . feel free to take a loot at issues.
