### ISSUE TITLE
add form validation in index page.

### ISSUE THREAD

**Issue by rajibmitra** [rajibmitra/simple-survey#41]
add form validation in index page.

e.g : 
email should have a format like abc@xyz.com.
mobile number should be digits. 
and except mobile number all are mandatory with * .

**Comment by LS05** [comment]
I'll work on this!

**Comment by rajibmitra** [comment]
Sure , go ahead.

**Comment by pacea87** [comment]
I just created a pull request for this issue.

**Comment by rajibmitra** [comment]
@pacea87  I really liked your front end validation part , but the design of these boxes are not equal , could you please fix that , then I will merge your PR.
